'use client';

import React, { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { Plan, PlanCreate, PlanUpdate } from '@/lib/types';
import {
  CheckSquare,
  Plus,
  Trash2,
  Calendar,
  Layers,
  Sparkles,
  Clock,
  CheckCircle2,
  AlertCircle,
  Tag,
  Filter
} from 'lucide-react';

export default function PlansPage() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterDomain, setFilterDomain] = useState<string>('all');
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newPlan, setNewPlan] = useState<PlanCreate>({
    title: '',
    description: '',
    domain: 'general',
    status: 'in_progress',
    due_date: '',
  });

  useEffect(() => {
    fetchPlans();
  }, []);

  const fetchPlans = async () => {
    setLoading(true);
    try {
      const data = await api.getPlans();
      setPlans(data);
    } catch (err) {
      console.error('Failed to load plans:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleCreatePlan = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newPlan.title.trim()) return;

    try {
      await api.createPlan(newPlan);
      setShowCreateModal(false);
      setNewPlan({
        title: '',
        description: '',
        domain: 'general',
        status: 'in_progress',
        due_date: '',
      });
      fetchPlans();
    } catch (err: any) {
      alert(`Error creating plan: ${err.message}`);
    }
  };

  const handleUpdateStatus = async (planId: string, newStatus: string) => {
    try {
      await api.updatePlan(planId, { status: newStatus });
      setPlans((prev) =>
        prev.map((p) => (p.id === planId ? { ...p, status: newStatus as any } : p))
      );
    } catch (err: any) {
      alert(`Error updating plan: ${err.message}`);
    }
  };

  const handleDeletePlan = async (planId: string) => {
    if (!confirm('Are you sure you want to delete this action plan?')) return;
    try {
      await api.deletePlan(planId);
      setPlans((prev) => prev.filter((p) => p.id !== planId));
    } catch (err: any) {
      alert(`Error deleting plan: ${err.message}`);
    }
  };

  const filteredPlans = plans.filter((p) => {
    if (filterDomain === 'all') return true;
    return p.domain === filterDomain;
  });

  const getDomainColor = (domain: string) => {
    switch (domain) {
      case 'finance':
        return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
      case 'study':
        return 'text-indigo-400 bg-indigo-500/10 border-indigo-500/20';
      case 'habit':
        return 'text-amber-400 bg-amber-500/10 border-amber-500/20';
      default:
        return 'text-teal-400 bg-teal-500/10 border-teal-500/20';
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'completed':
        return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20';
      case 'in_progress':
        return 'bg-sky-500/10 text-sky-400 border-sky-500/20';
      case 'pending':
      case 'proposed':
        return 'bg-amber-500/10 text-amber-400 border-amber-500/20';
      default:
        return 'bg-slate-800 text-slate-400 border-slate-700';
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 p-6 rounded-2xl bg-slate-900/60 border border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-teal-500/10 border border-teal-500/20 flex items-center justify-center text-teal-400">
            <CheckSquare className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-white">Action Plans Tracker</h1>
            <p className="text-xs text-slate-400">
              Approved milestones generated by Gemini tool calling or configured manually.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Domain Filter */}
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-300">
            <Filter className="w-3.5 h-3.5 text-slate-500" />
            <select
              value={filterDomain}
              onChange={(e) => setFilterDomain(e.target.value)}
              className="bg-transparent outline-none text-xs text-slate-300 cursor-pointer"
            >
              <option value="all" className="bg-slate-900">All Domains</option>
              <option value="finance" className="bg-slate-900">Finance</option>
              <option value="study" className="bg-slate-900">Study</option>
              <option value="habit" className="bg-slate-900">Habit</option>
              <option value="general" className="bg-slate-900">General</option>
            </select>
          </div>

          <button
            onClick={() => setShowCreateModal(true)}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-teal-600 hover:bg-teal-500 text-white text-xs font-semibold transition shadow-md"
          >
            <Plus className="w-4 h-4" />
            <span>New Action Plan</span>
          </button>
        </div>
      </div>

      {/* Plans List / Grid */}
      {loading ? (
        <div className="p-12 text-center flex flex-col items-center gap-3">
          <div className="w-8 h-8 border-3 border-teal-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-xs text-slate-500">Loading action plans...</p>
        </div>
      ) : filteredPlans.length === 0 ? (
        <div className="p-12 rounded-2xl bg-slate-900/40 border border-slate-800 text-center flex flex-col items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-slate-800/80 flex items-center justify-center text-slate-500">
            <CheckSquare className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-white">No Action Plans Found</h3>
            <p className="text-xs text-slate-400 mt-1 max-w-sm">
              Ask the Gemini Digital Twin assistant in Chat to formulate a structured plan, or add one manually above!
            </p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredPlans.map((plan) => (
            <div
              key={plan.id}
              className="p-5 rounded-2xl bg-slate-900/60 border border-slate-800 flex flex-col justify-between space-y-4 hover:border-slate-700 transition group"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span
                    className={`px-2 py-0.5 rounded-md text-[10px] font-semibold uppercase tracking-wider border ${getDomainColor(
                      plan.domain
                    )}`}
                  >
                    {plan.domain}
                  </span>
                  <select
                    value={plan.status}
                    onChange={(e) => handleUpdateStatus(plan.id, e.target.value)}
                    className={`text-[11px] font-medium px-2 py-0.5 rounded-full border bg-slate-950 outline-none cursor-pointer ${getStatusBadge(
                      plan.status
                    )}`}
                  >
                    <option value="pending" className="bg-slate-900 text-slate-300">Pending</option>
                    <option value="in_progress" className="bg-slate-900 text-slate-300">In Progress</option>
                    <option value="completed" className="bg-slate-900 text-slate-300">Completed</option>
                    <option value="cancelled" className="bg-slate-900 text-slate-300">Cancelled</option>
                  </select>
                </div>

                <h3 className="text-sm font-bold text-white group-hover:text-teal-300 transition">
                  {plan.title}
                </h3>

                {plan.description && (
                  <p className="text-xs text-slate-400 leading-relaxed line-clamp-3">
                    {plan.description}
                  </p>
                )}
              </div>

              <div className="pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-500">
                <div className="flex items-center gap-1.5">
                  <Calendar className="w-3.5 h-3.5 text-slate-500" />
                  <span>{plan.due_date ? plan.due_date : 'No deadline'}</span>
                </div>

                <button
                  onClick={() => handleDeletePlan(plan.id)}
                  className="p-1.5 rounded-lg text-slate-500 hover:text-rose-400 hover:bg-rose-500/10 transition"
                  title="Delete Plan"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-md p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4 shadow-xl">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-bold text-white">Create New Action Plan</h3>
              <button
                onClick={() => setShowCreateModal(false)}
                className="text-slate-400 hover:text-white text-xs"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleCreatePlan} className="space-y-3.5 text-xs">
              <div>
                <label className="block text-slate-400 mb-1 font-medium">Plan Title *</label>
                <input
                  type="text"
                  required
                  value={newPlan.title}
                  onChange={(e) => setNewPlan({ ...newPlan, title: e.target.value })}
                  placeholder="e.g. Save $500 monthly for emergency fund"
                  className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white outline-none focus:border-teal-500"
                />
              </div>

              <div>
                <label className="block text-slate-400 mb-1 font-medium">Description</label>
                <textarea
                  rows={3}
                  value={newPlan.description}
                  onChange={(e) => setNewPlan({ ...newPlan, description: e.target.value })}
                  placeholder="Specific actionable steps or strategies..."
                  className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white outline-none focus:border-teal-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-slate-400 mb-1 font-medium">Domain</label>
                  <select
                    value={newPlan.domain}
                    onChange={(e) => setNewPlan({ ...newPlan, domain: e.target.value })}
                    className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white outline-none focus:border-teal-500"
                  >
                    <option value="general">General</option>
                    <option value="finance">Finance</option>
                    <option value="study">Study</option>
                    <option value="habit">Habit</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-400 mb-1 font-medium">Target Date</label>
                  <input
                    type="date"
                    value={newPlan.due_date}
                    onChange={(e) => setNewPlan({ ...newPlan, due_date: e.target.value })}
                    className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white outline-none focus:border-teal-500"
                  />
                </div>
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 font-medium transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-xl bg-teal-600 hover:bg-teal-500 text-white font-semibold transition"
                >
                  Create Plan
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
