[project]
name = "digital-twin-ai"
version = "1.0.0"
description = "Personal AI Life Simulator & Cross-Domain Digital Twin"

[tool.pyright]
include = ["backend", "ml"]
extraPaths = ["./backend", "./ml", "C:/coding files/Lib/site-packages"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "backend/tests",
]
pythonpath = [
    "backend",
    "ml"
]
