import os
import re

# Paths
brain_dir = r"C:\Users\HP\.gemini\antigravity-ide\brain\4291392f-aef1-4e73-a59d-edb8a30ddafe"
part1 = os.path.join(brain_dir, "project_documentation_part1.md")
part2 = os.path.join(brain_dir, "project_documentation_part2.md")
part3 = os.path.join(brain_dir, "project_documentation_part3.md")
output_md = r"d:\AI-Based-Virtual-Risk-and-Compliance\docs\Final_Project_Report.md"

def read_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

# Load parts
content1 = read_file(part1)
content2 = read_file(part2)
content3 = read_file(part3)

# Strip out the redundant table of contents and headers from part 1, 2, 3
content1 = re.sub(r"# AI-Based Virtual Risk.*?(?=# 1\. )", "", content1, flags=re.DOTALL)
content2 = re.sub(r"# AI-Based Virtual Risk.*?(?=# 11\. )", "", content2, flags=re.DOTALL)
content3 = re.sub(r"# AI-Based Virtual Risk.*?(?=# 21\. )", "", content3, flags=re.DOTALL)

# Combine
full_content = content1 + "\n\n" + content2 + "\n\n" + content3

# Replace "# 1. Title" with "# Chapter 1 — Title"
full_content = re.sub(r"^# (\d+)\.\s+(.*)$", r"# Chapter \1 — \2", full_content, flags=re.MULTILINE)

# Front matter
front_matter = """---
pdf_options:
  format: a4
  margin: 30mm 20mm
  printBackground: true
---

<div style="text-align: center; margin-top: 100px;">
    <h1>AI-Based Virtual Risk and Compliance Intelligence System</h1>
    <br><br>
    <h2>A Final Year B.E. Computer Science Engineering Project Report</h2>
    <br><br>
    <h3>Submitted by</h3>
    <p>Student Name</p>
    <br><br>
    <h3>Department of Computer Science and Engineering</h3>
    <br><br>
    <p>Academic Year: 2026–2027</p>
</div>

<div style="page-break-after: always;"></div>

## Certificate

This is to certify that the project report entitled **"AI-Based Virtual Risk and Compliance Intelligence System"** is a bonafide record of the work carried out by the student in partial fulfillment for the award of Bachelor of Engineering in Computer Science and Engineering during the academic year 2026-2027.

<br><br><br><br>
<div style="display: flex; justify-content: space-between;">
    <div><strong>Signature of Guide</strong></div>
    <div><strong>Signature of HOD</strong></div>
</div>

<div style="page-break-after: always;"></div>

## Declaration

I hereby declare that the project report entitled **"AI-Based Virtual Risk and Compliance Intelligence System"** is an authentic record of my own work carried out during the academic year 2026-2027 under the guidance of the faculty supervisor. The matter embodied in this report has not been submitted by me for the award of any other degree or diploma.

<br><br><br>
**Signature:** _______________ <br>
**Name:** ___________________ <br>
**Date:** ___________________

<div style="page-break-after: always;"></div>

## Acknowledgement

I would like to express my sincere gratitude to my project guide and the Department of Computer Science and Engineering for their continuous support, encouragement, and guidance throughout this project. 

I also extend my thanks to all those who have directly or indirectly helped me in the successful completion of this project.

<div style="page-break-after: always;"></div>

## Abstract

The AI-Based Virtual Risk and Compliance Intelligence System, internally designated as Digital Twin AI, is a full-stack web application designed to construct an isolated, per-user digital twin. By synthesizing data from three distinct but interconnected life domains—personal finance, academic performance, and habit/wellbeing consistency—the system provides a unified intelligence platform. 

Current personal tracking tools operate in silos, failing to capture the cross-domain ripple effects of human decision-making, such as the impact of sleep deprivation on academic retention, or financial anxiety on habit adherence. This project addresses this fragmentation through machine learning forecasting (using Ridge Regression, Random Forest, and Calibrated Logistic Regression), stochastic Monte Carlo counterfactual simulation capable of executing up to 15,000 vectorized iterations, deterministic rule-based recommendations, and an autonomous tool-calling AI conversational agent.

Built with Next.js 14, FastAPI, PostgreSQL, and orchestrated via Docker Compose, the system ensures data privacy through GDPR/CCPA compliance, JWT authentication, and strict tenant isolation. The project successfully demonstrates that cross-domain synthesis yields highly actionable insights that single-domain applications cannot provide.

<div style="page-break-after: always;"></div>

## Table of Contents
*Will be generated by the PDF renderer or document viewer.*

<div style="page-break-after: always;"></div>

## List of Figures
- Fig. 24.1: Dashboard overview displaying composite Life Path Index score
- Fig. 24.2: Dashboard overview demonstrating theme adaptability with light theme
- Fig. 24.3: Mobile-responsive dashboard layout with hamburger navigation drawer
- Fig. 24.4: Interactive tooltip displaying mathematical weighting formula
- Fig. 24.5: Personal finance management interface with transaction CRUD
- Fig. 24.6: Finance ledger demonstrating light theme with cash flow trend chart
- Fig. 24.7: Collapsible quick-entry panel for finance transaction input
- Fig. 24.8: Study session quick-entry panel with subject, hours, and optional score
- Fig. 24.9: Habit log quick-entry panel with sleep, exercise, and mood inputs
- Fig. 24.10: AI conversational assistant displaying tool execution badges
- Fig. 24.11: AI assistant demonstrating multi-turn tool calling with chart
- Fig. 24.12: Confirmation dialog for chat history clearing
- Fig. 24.13: Action plan management board with status columns
- Fig. 24.14: Action plan Kanban board demonstrating AI-proposed plan integration
- Fig. 24.15: Deterministic recommendation cards with grounded metric citations
- Fig. 24.16: Cross-domain recommendation interface with dismiss/act functionality
- Fig. 24.17: Account settings page with profile editor
- Fig. 24.18: Settings interface demonstrating currency preference
- Fig. 24.19: Multi-tab history interface showing login audit trail
- Fig. 24.20: History data grid with inline editing and pagination controls
- Fig. 24.21: Mobile-responsive AI assistant interface
- Fig. 24.22: Mobile-responsive action plan board
- Fig. 24.23: Mobile-responsive recommendation cards
- Fig. 24.24: Mobile-responsive settings page
- Fig. 24.25: Mobile dashboard demonstrating responsive stat tile layout

<div style="page-break-after: always;"></div>

## List of Tables
- Table 2.1: Functional Requirements
- Table 2.2: Non-Functional Requirements
- Table 2.3: Hardware Requirements
- Table 2.4: Software Requirements
- Table 4.1: Core Domain Models (SQLAlchemy ORM)
- Table 4.2: Service Classes
- Table 4.3: Data Flow Diagram (Level 1)
- Table 6.1 - 6.13: Database Table Definitions
- Table 9.1 - 9.3: ML Model Performance Metrics
- Table 11.1: Shock Generation Models
- Table 14.1: AI Chatbot Tools
- Table 16.1 - 16.12: API Endpoint Catalog
- Table 21.1 - 21.8: Test Case Specifications
- Table 26.1: Measured Performance Metrics

<div style="page-break-after: always;"></div>

"""

final_doc = front_matter + full_content

# Add References section before Appendices
final_doc = final_doc.replace("# Chapter 31 — Appendices", "## References\n\n1. Next.js Documentation. Vercel. https://nextjs.org/docs\n2. FastAPI Documentation. https://fastapi.tiangolo.com/\n3. Scikit-learn: Machine Learning in Python, Pedregosa et al., JMLR 12, pp. 2825-2830, 2011.\n4. Recharts: A composable charting library built on React components. https://recharts.org/\n5. SQLAlchemy 2.0 Documentation. https://docs.sqlalchemy.org/en/20/\n\n<div style=\"page-break-after: always;\"></div>\n\n# Appendices")

with open(output_md, "w", encoding="utf-8") as f:
    f.write(final_doc)

print("Markdown compiled successfully.")
